name: DisplayTypeValues
description: "DISPLAY_TYPE should use standard ISTP values"
url: "https://istp-metadata.readthedocs.io/en/latest/source/05_metadata-variable-attributes.html#display_type"
reference: "ISTP-VA-005"
severity: WARNING
suite: ISTP

assertions:
  - path: "variables/.*/attributes/DISPLAY_TYPE/values/[0-9]*"
    check: in
    error_if_no_match: false
    values:
      - time_series
      - spectrogram
      - stack_plot
      - image
      - no_plot
      - orbit
      - plasmagram
      - movie
    message: "{% if valid %}Attribute DISPLAY_TYPE of {{ variable }} has value '{{ value }}'{% else %}Attribute DISPLAY_TYPE of {{ variable }} has value '{{ value }}', expected time_series, spectrogram, stack_plot, image, no_plot, orbit, plasmagram, or movie{% endif %}"

