name: ScaleTypValues
description: "SCALETYP should be 'linear' or 'log' for proper plotting"
url: "https://istp-metadata.readthedocs.io/en/latest/source/05_metadata-variable-attributes.html#scaletyp"
reference: "ISTP-VA-013"
severity: WARNING
suite: ISTP

assertions:
  - path: "variables/.*/attributes/SCALETYP/values/[0-9]*"
    check: in
    error_if_no_match: false
    values:
      - linear
      - log
    message: "{% if valid %}Attribute SCALETYP of {{ variable }} has value '{{ value }}'{% else %}Attribute SCALETYP of {{ variable }} has value '{{ value }}', expected 'linear' or 'log'{% endif %}"

