name: VarTypeValues
description: "VAR_TYPE must be one of the allowed ISTP values"
url: "https://istp-metadata.readthedocs.io/en/latest/source/05_metadata-variable-attributes.html#var-type"
reference: "ISTP-VA-004"
severity: ERROR
suite: ISTP

assertions:
  - path: "variables/.*/attributes/VAR_TYPE/values/[0-9]*"
    check: in
    values:
      - data
      - support_data
      - metadata
      - ignore_data
    message: "{% if valid %}Attribute VAR_TYPE of {{ variable }} has value '{{ value }}'{% else %}Attribute VAR_TYPE of {{ variable }} has value '{{ value }}', expected 'data', 'support_data', 'metadata', or 'ignore_data'{% endif %}"

