name: DisciplineValues
description: "Discipline should use standard ISTP values"
url: "https://istp-metadata.readthedocs.io/en/latest/source/03_metadata-global-attributes.html#discipline"
reference: "ISTP-GA-009"
severity: WARNING
suite: ISTP

assertions:
  - path: "attributes/Discipline/values/[0-9]*"
    check: in
    error_if_no_match: false
    values:
      - "Solar Physics>Heliospheric Physics"
      - "Space Physics>Interplanetary Studies"
      - "Space Physics>Magnetospheric Science"
      - "Space Physics>Ionospheric Science"
      - "Space Physics>Astrophysics Science"
    message: "Discipline should use a standard ISTP value (e.g., 'Space Physics>Magnetospheric Science')"

