name: InstrumentTypeValues
description: "Instrument_type should use standard ISTP values"
url: "https://istp-metadata.readthedocs.io/en/latest/source/03_metadata-global-attributes.html#instrument-type"
reference: "ISTP-GA-010"
severity: WARNING
suite: ISTP

assertions:
  - path: "attributes/Instrument_type/values/[0-9]*"
    check: in
    error_if_no_match: false
    values:
      - "Activity Indices"
      - "Dust and Debris"
      - "Electric Fields (space)"
      - "Engineering"
      - "Ephemeris/Attitude/Ancillary"
      - "Ground-Based HF-Radars"
      - "Ground-Based Imagers"
      - "Ground-Based Magnetometers, Riometers, Sounders"
      - "Ground-Based VLF/ELF/ULF, Photometers"
      - "Housekeeping"
      - "Imaging and Remote Sensing (ITM/Earth)"
      - "Imaging and Remote Sensing (Magnetosphere/Earth)"
      - "Imaging and Remote Sensing (Sun)"
      - "Magnetic Fields (Balloon)"
      - "Magnetic Fields (space)"
      - "Particles (space)"
      - "Plasma and Solar Wind"
      - "Radio and Plasma Waves (space)"
    message: "{% if valid %}Instrument_type uses a standard ISTP value{% else %}Instrument_type should use a standard ISTP value{% endif %}"

